const mongoose = require("mongoose");

const documentEmbeddingSchema = new mongoose.Schema(
  {
    projectId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Project",
      required: [true, "projectId is required"],
      index: true,
    },
    fileId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "File",
      required: [true, "fileId is required"],
      index: true,
    },
    chunkIndex: {
      type: Number,
      required: [true, "chunkIndex is required"],
      min: [0, "chunkIndex must be a non-negative integer"],
    },
    textContent: {
      type: String,
      required: [true, "textContent is required"],
    },
    embedding: {
      type: [Number],
      required: [true, "embedding is required"],
      validate: {
        /**
         * Strictly enforces the dimensionality constraints required by the underlying vector database architecture (e.g., OpenAI embeddings).
         * This validation hook runs immediately before saving a new document embedding chunk. In vector search methodologies, 
         * cosine similarity and dot product calculations depend entirely on uniform vector lengths across the entire dataset. 
         * The current AI model configuration dictates that all vector representations must consist of exactly 1,536 floating-point numbers.
         *
         * If the incoming array generated by the machine learning API is malformed, truncated, or from an incompatible model 
         * (e.g., resulting in 768 or 3072 dimensions), this validator will intercept and reject the data. 
         * This critical check prevents corrupted vector spaces which would otherwise lead to catastrophic failures during similarity search queries, 
         * ensuring the integrity of the RAG (Retrieval-Augmented Generation) system.
         *
         * @param {Array<Number>} v - The raw array of floating-point numbers representing the dense vector embedding of the text chunk.
         * @returns {boolean} Returns `true` exclusively when the array length is exactly 1536, preventing anomalies; otherwise returns `false`.
         * @throws {ValidationError} Emits a schema Validation Error (HTTP 400/500 depending on handling) if the dimensions mismatch.
         */
        validator: (v) => v.length === 1536,
        message: "embedding must have exactly 1536 dimensions",
      },
    },
    metadata: {
      pageNumber: {
        type: Number,
        default: null,
      },
      audioTimestamp: {
        type: String,
        default: null,
        match: [/^\d{1,2}:\d{2}$/, "audioTimestamp must be in MM:SS format"],
      },
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "createdBy is required"],
    },
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  {
    timestamps: true, // auto-manages createdAt & updatedAt
  }
);

// Compound index for fast chunk retrieval per file
documentEmbeddingSchema.index({ fileId: 1, chunkIndex: 1 });

// Compound index for fast queries per project
documentEmbeddingSchema.index({ projectId: 1, fileId: 1 });

module.exports = mongoose.model("DocumentEmbedding", documentEmbeddingSchema);
